# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

volumes: 
  datafiles:

services:
  database:
    # pull the latest mysql image
    image: mysql:8.0.22
    # map port 3306 on the mysql container to port 3306in the host
    ports: 
      - "3306:3306"
    # specify were the persisted Data should be stored
    volumes: 
      - datafiles:/var/lib/mysql
      # We copy the initial script to be run automatically
      - "~/sql-scripts/setup/sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    # Specify Environment Variables for mysql
    # The user by default will have admin rights
    environment: 
      MYSQL_ROOT_PASSWORD: Root0++
      MYSQL_USER: newuser
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: storedb
  
  # API Service
  api:
    image: api
    build:
      context: .
      # Use the docker file in that directory
      dockerfile: Dockerfile
    # This service depende on the database service specified above
    depends_on: 
      - database
    # Map port 8888 in the docker container to port 80 in the API
    ports:
      - "5000:80"
    restart: always
    # Specify Environment Variables for the API Service
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

# Angular Service
  angular:
    container_name: angular
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - './products-store:/usr/src/app'
    ports:
      - '4201:4200'